let market={stocks:[],favourites:[]};let journal=JSON.parse(localStorage.getItem("stockstory_journal")||"[]");
async function load(){try{market=await (await fetch("data/market.json?x="+Date.now())).json()}catch(e){market={stocks:[],favourites:[]}}render()}
function money(v){return v==null?"—":"₹"+Number(v).toLocaleString("en-IN",{maximumFractionDigits:2})}
function vol(v){if(v==null)return"—";v=Number(v);if(v>=1e7)return(v/1e7).toFixed(2)+" Cr";if(v>=1e5)return(v/1e5).toFixed(2)+" L";if(v>=1e3)return(v/1e3).toFixed(1)+" K";return v.toLocaleString("en-IN")}
function render(){let s=market.stocks||[];document.getElementById("count").textContent=s.length;document.getElementById("updated").textContent=market.updated?new Date(market.updated).toLocaleTimeString("en-IN",{hour:"2-digit",minute:"2-digit"}):"—";let fav=new Set((market.favourites||[]));let f=s.filter(x=>fav.has(x.symbol));document.getElementById("fav").innerHTML=f.map(card).join("")||'<div class="empty">Add symbols to data/stocks.json and they will appear here.</div>';document.getElementById("scan").innerHTML=s.slice().sort((a,b)=>(b.setupScore||0)-(a.setupScore||0)).slice(0,60).map(card).join("")||'<div class="empty">Run the GitHub Action first.</div>';renderJournal()}
function card(s){return `<article class="card"><div class="top"><div><div class="symbol">${s.symbol}</div><div class="company">${s.company||""}</div></div><div><span class="badge">UPSTOX</span><div class="price">${money(s.price)}</div></div></div><div class="metrics"><div class="metric"><small>DAY HIGH</small><strong>${money(s.high)}</strong></div><div class="metric"><small>DAY LOW</small><strong>${money(s.low)}</strong></div><div class="metric"><small>VOLUME</small><strong>${vol(s.volume)}</strong></div><div class="metric"><small>20D AVG</small><strong>${vol(s.average20Volume)}</strong></div><div class="metric"><small>RELATIVE VOL</small><strong class="${s.volumeShocker?"warning":""}">${s.relativeVolume==null?"—":s.relativeVolume.toFixed(2)+"×"} ${s.volumeShocker?"🔥":""}</strong></div><div class="metric"><small>52W HIGH</small><strong>${money(s.yearlyHigh)}</strong></div><div class="metric"><small>ATH</small><strong>${money(s.ath)}</strong></div><div class="metric"><small>SETUP SCORE</small><strong>${s.setupScore??"—"}/10</strong></div></div>${(s.tags||[]).map(t=>`<span class="tag">${t}</span>`).join("")}<p class="thesis">${s.thesis||"NSE scanner candidate."}</p></article>`}
document.querySelectorAll("nav button").forEach(b=>b.onclick=()=>{document.querySelectorAll("nav button").forEach(x=>x.classList.remove("active"));document.querySelectorAll(".page").forEach(x=>x.classList.remove("active"));b.classList.add("active");document.getElementById(b.dataset.page).classList.add("active")});
function addTrade(){let symbol=prompt("Stock symbol?");if(!symbol)return;let reason=prompt("Reason / setup?")||"";journal.unshift({date:new Date().toISOString(),symbol:symbol.toUpperCase(),reason});localStorage.setItem("stockstory_journal",JSON.stringify(journal));renderJournal()}
function renderJournal(){document.getElementById("journalList").innerHTML=journal.map(t=>`<div class="journal"><div><b>${t.symbol}</b><div class="muted">${new Date(t.date).toLocaleDateString("en-IN")}</div><p>${t.reason}</p></div></div>`).join("")||'<div class="empty">No trades recorded yet.</div>'}
load()