let market={stocks:[]};let journal=JSON.parse(localStorage.getItem("stockstory_journal")||"[]");
async function load(){try{const r=await fetch("data/market.json?x="+Date.now());market=await r.json();}catch(e){market={stocks:[]}}render();renderJournal()}
function money(v){return v==null?"—":"₹"+Number(v).toLocaleString("en-IN",{maximumFractionDigits:2})}
function vol(v){if(v==null)return"—";v=Number(v);if(v>=1e7)return(v/1e7).toFixed(2)+" Cr";if(v>=1e5)return(v/1e5).toFixed(2)+" L";if(v>=1e3)return(v/1e3).toFixed(1)+" K";return v.toLocaleString("en-IN")}
function render(){document.getElementById("count").textContent=market.stocks.length;document.getElementById("updated").textContent=market.updated?new Date(market.updated).toLocaleTimeString("en-IN",{hour:"2-digit",minute:"2-digit"}):"—";document.getElementById("stocks").innerHTML=market.stocks.map(s=>card(s)).join("")||'<div class="empty">No market data yet. Run the GitHub Action.</div>';let v=market.stocks.filter(s=>s.volumeShocker);let a=market.stocks.filter(s=>s.nearATH||s.newATH);document.getElementById("scannerCards").innerHTML=`<div class="card"><h3>🔥 Volume Shockers</h3><p>${v.length?v.map(s=>s.symbol+" "+s.relativeVolume.toFixed(2)+"×").join("<br>"):"None yet"}</p></div><div class="card"><h3>🚀 Near / New ATH</h3><p>${a.length?a.map(s=>s.symbol+" "+s.distanceFromATH.toFixed(1)+"% below ATH").join("<br>"):"None yet"}</p></div><div class="card"><h3>🏆 52W</h3><p>52-week scanner is the next enhancement.</p></div>`}
function card(s){return `<article class="card"><div class="top"><div><div class="symbol">${s.symbol}</div><div class="company">${s.company||""}</div></div><div>${s.price!=null?'<span class="badge">DATA</span>':""}<div class="price">${money(s.price)}</div></div></div><div class="metrics"><div class="metric"><small>DAY HIGH</small><strong>${money(s.high)}</strong></div><div class="metric"><small>DAY LOW</small><strong>${money(s.low)}</strong></div><div class="metric"><small>VOLUME</small><strong>${vol(s.volume)}</strong></div><div class="metric"><small>20D AVG</small><strong>${vol(s.average20Volume)}</strong></div><div class="metric"><small>RELATIVE VOLUME</small><strong class="${s.volumeShocker?"warning":""}">${s.relativeVolume==null?"—":s.relativeVolume.toFixed(2)+"×"} ${s.volumeShocker?"🔥":""}</strong></div><div class="metric"><small>ATH</small><strong>${money(s.ath)}</strong></div><div class="metric"><small>FROM ATH</small><strong>${s.distanceFromATH==null?"—":s.distanceFromATH.toFixed(1)+"%"}</strong></div><div class="metric"><small>SETUP SCORE</small><strong>${s.setupScore??"—"}/10</strong></div></div><div>${(s.tags||[]).map(t=>`<span class="tag">${t}</span>`).join("")}</div><p class="thesis">${s.thesis||"Add your reason for watching this stock."}</p></article>`}
document.querySelectorAll("nav button").forEach(b=>b.onclick=()=>{document.querySelectorAll("nav button").forEach(x=>x.classList.remove("active"));document.querySelectorAll(".page").forEach(x=>x.classList.remove("active"));b.classList.add("active");document.getElementById(b.dataset.page).classList.add("active")});
function refresh(){load()}
function addTrade(){const symbol=prompt("Stock symbol?");if(!symbol)return;const reason=prompt("Reason / setup?")||"";journal.unshift({date:new Date().toISOString(),symbol:symbol.toUpperCase(),reason});localStorage.setItem("stockstory_journal",JSON.stringify(journal));renderJournal()}
function renderJournal(){document.getElementById("journalList").innerHTML=journal.map(t=>`<div class="journal"><div><b>${t.symbol}</b><div class="muted">${new Date(t.date).toLocaleDateString("en-IN")}</div><p>${t.reason}</p></div></div>`).join("")||'<div class="empty">No trades recorded yet.</div>'}
load()
