const STOCK_KEY="stockstory_watchlist_v1", JOURNAL_KEY="stockstory_journal_v1";
let stocks=JSON.parse(localStorage.getItem(STOCK_KEY)||"null"), journal=JSON.parse(localStorage.getItem(JOURNAL_KEY)||"[]");
if(!Array.isArray(stocks)){stocks=[{id:crypto.randomUUID(),symbol:"NSE:JYOTICNC",company:"JYOTI CNC AUTOMATION LTD",sector:"",setup:"Trendline Breakout",level:"",entry:"",stop:"",target:"",chartink:"",tradingview:"",why:"Price has broken the long-term descending trendline.",notes:"",favourite:true}];saveStocks()}
const esc=v=>String(v??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]));
const money=v=>v!==null&&v!==undefined&&String(v).trim()!==""?"₹"+esc(v):"—";
function saveStocks(){localStorage.setItem(STOCK_KEY,JSON.stringify(stocks))} function persistJournal(){localStorage.setItem(JOURNAL_KEY,JSON.stringify(journal))}
function render(){const q=(document.getElementById("searchBox")?.value||"").toLowerCase(),f=document.getElementById("favFilter")?.value||"all";const filtered=stocks.filter(s=>JSON.stringify(s).toLowerCase().includes(q)&&(f==="all"||s.favourite));document.getElementById("count").textContent=stocks.length;document.getElementById("favCount").textContent=stocks.filter(s=>s.favourite).length;document.getElementById("fav").innerHTML=stocks.filter(s=>s.favourite).map(card).join("")||'<div class="empty">No favourite stocks yet. Add one using + Add Stock.</div>';document.getElementById("allStocks").innerHTML=filtered.map(card).join("")||'<div class="empty">No stocks found.</div>';document.getElementById("storyList").innerHTML=stocks.map(storyCard).join("")||'<div class="empty">Add a stock to create its story.</div>';renderJournal()}
function card(s){return `<article class="card"><div class="top"><div><div class="symbol">${esc(s.symbol)}</div><div class="company">${esc(s.company||"")}</div></div><div><span class="badge">${s.favourite?"FAVOURITE":"WATCH"}</span><div class="price">${money(s.level)}</div></div></div><div class="metrics"><div class="metric"><small>SETUP</small><strong>${esc(s.setup||"—")}</strong></div><div class="metric"><small>LEVEL</small><strong>${money(s.level)}</strong></div><div class="metric"><small>ENTRY</small><strong>${money(s.entry)}</strong></div><div class="metric"><small>STOP LOSS</small><strong>${money(s.stop)}</strong></div><div class="metric"><small>TARGET</small><strong>${money(s.target)}</strong></div><div class="metric"><small>SECTOR</small><strong>${esc(s.sector||"—")}</strong></div></div>${s.setup?`<span class="tag">${esc(s.setup)}</span>`:""}<p class="thesis">${esc(s.why||"Add why this stock is interesting.")}</p><div class="card-actions"><button onclick="editStock('${s.id}')">Edit</button><button onclick="toggleFavourite('${s.id}')">${s.favourite?"★ Favourite":"☆ Favourite"}</button>${s.chartink?`<a target="_blank" href="${esc(s.chartink)}">Chartink</a>`:""}${s.tradingview?`<a target="_blank" href="${esc(s.tradingview)}">TradingView</a>`:""}<button onclick="deleteStock('${s.id}')">Delete</button></div></article>`}
function storyCard(s){return `<article class="card"><div class="top"><div><div class="symbol">${esc(s.symbol)}</div><div class="company">${esc(s.company||"")}</div></div><div>${s.favourite?"⭐":""}</div></div><div class="metrics"><div class="metric"><small>SETUP</small><strong>${esc(s.setup||"—")}</strong></div><div class="metric"><small>WATCH LEVEL</small><strong>${money(s.level)}</strong></div><div class="metric"><small>ENTRY</small><strong>${money(s.entry)}</strong></div><div class="metric"><small>STOP</small><strong>${money(s.stop)}</strong></div><div class="metric"><small>TARGET</small><strong>${money(s.target)}</strong></div><div class="metric"><small>SECTOR</small><strong>${esc(s.sector||"—")}</strong></div></div><p class="thesis"><b>Why I'm watching:</b><br>${esc(s.why||"—")}</p><p class="thesis"><b>My notes:</b><br>${esc(s.notes||"—")}</p><div class="card-actions"><button onclick="editStock('${s.id}')">Edit Story</button>${s.chartink?`<a target="_blank" href="${esc(s.chartink)}">Chartink</a>`:""}${s.tradingview?`<a target="_blank" href="${esc(s.tradingview)}">TradingView</a>`:""}</div></article>`}
function openStockForm(s=null){document.getElementById("stockModalTitle").textContent=s?"Edit Stock":"Add Stock";const m={stockId:s?.id||"",fSymbol:s?.symbol||"",fCompany:s?.company||"",fSector:s?.sector||"",fSetup:s?.setup||"",fLevel:s?.level||"",fEntry:s?.entry||"",fStop:s?.stop||"",fTarget:s?.target||"",fChartink:s?.chartink||"",fTradingView:s?.tradingview||"",fWhy:s?.why||"",fNotes:s?.notes||""};Object.entries(m).forEach(([id,v])=>document.getElementById(id).value=v);document.getElementById("fFavourite").checked=!!s?.favourite;document.getElementById("stockModal").classList.remove("hidden")}
function saveStock(e){e.preventDefault();const id=fSymbol.value.trim().toUpperCase();if(!id)return;const x={id:document.getElementById("stockId").value||crypto.randomUUID(),symbol:id,company:fCompany.value.trim(),sector:fSector.value.trim(),setup:fSetup.value.trim(),level:fLevel.value.trim(),entry:fEntry.value.trim(),stop:fStop.value.trim(),target:fTarget.value.trim(),chartink:fChartink.value.trim(),tradingview:fTradingView.value.trim(),why:fWhy.value.trim(),notes:fNotes.value.trim(),favourite:fFavourite.checked};const old=document.getElementById("stockId").value;if(old)stocks=stocks.map(s=>s.id===old?x:s);else stocks.push(x);saveStocks();closeModals();render()}
function editStock(id){openStockForm(stocks.find(s=>s.id===id))} function deleteStock(id){const s=stocks.find(x=>x.id===id);if(s&&confirm(`Delete ${s.symbol}?`)){stocks=stocks.filter(x=>x.id!==id);saveStocks();render()}} function toggleFavourite(id){const s=stocks.find(x=>x.id===id);if(s){s.favourite=!s.favourite;saveStocks();render()}}
function showAllStocks(){document.querySelector('[data-page="watch"]').click();document.getElementById("favFilter").value="all";document.getElementById("searchBox").focus()}
function openJournalForm(){jDate.value=new Date().toISOString().slice(0,10);[jMarket,jStocks,jTrades,jLesson,jNotes].forEach(x=>x.value="");document.getElementById("journalModal").classList.remove("hidden")}
function saveJournal(e){e.preventDefault();journal.unshift({id:crypto.randomUUID(),date:jDate.value,market:jMarket.value.trim(),stocks:jStocks.value.trim(),trades:jTrades.value.trim(),lesson:jLesson.value.trim(),notes:jNotes.value.trim()});persistJournal();closeModals();renderJournal()}
function renderJournal(){document.getElementById("journalList").innerHTML=journal.length?journal.map(j=>`<div class="journal"><div><b>${esc(j.date)}</b><div class="muted">${esc(j.market||"")}</div></div>${j.stocks?`<p><b>Stocks Watching</b><br>${esc(j.stocks)}</p>`:""}${j.trades?`<p><b>Trades / Actions</b><br>${esc(j.trades)}</p>`:""}${j.lesson?`<p><b>What I Learned</b><br>${esc(j.lesson)}</p>`:""}${j.notes?`<p><b>Notes</b><br>${esc(j.notes)}</p>`:""}<button onclick="deleteJournal('${j.id}')">Delete</button></div>`).join(""):'<div class="empty">No journal entries yet.</div>'}
function deleteJournal(id){if(confirm("Delete this journal entry?")){journal=journal.filter(x=>x.id!==id);persistJournal();renderJournal()}}
function parseCSVLine(l){const a=[];let c="",q=false;for(let i=0;i<l.length;i++){if(l[i]==='"'&&l[i+1]==='"'){c+='"';i++;continue}if(l[i]==='"'){q=!q;continue}if(l[i]===','&&!q){a.push(c.trim());c=""}else c+=l[i]}a.push(c.trim());return a}
function importCSV(e){const file=e.target.files[0];if(!file)return;const r=new FileReader();r.onload=()=>{const lines=r.result.replace(/\r/g,"").split("\n").filter(Boolean);const h=parseCSVLine(lines[0]).map(x=>x.toLowerCase().replace(/\s+/g,""));const rows=lines.slice(1).map(l=>{const v=parseCSVLine(l),o={};h.forEach((k,i)=>o[k]=v[i]||"");return{id:crypto.randomUUID(),symbol:(o.symbol||o.ticker||"").toUpperCase(),company:o.company||"",sector:o.sector||"",setup:o.setup||"",level:o.level||o.leveltowatch||"",entry:o.entry||"",stop:o.stop||o.stoploss||"",target:o.target||"",chartink:o.chartink||"",tradingview:o.tradingview||"",why:o.why||o.whyimwatching||"",notes:o.notes||"",favourite:["true","yes","1","y"].includes((o.favourite||"").toLowerCase())}}).filter(x=>x.symbol);if(!rows.length){alert("CSV must contain a Symbol column.");return}stocks.push(...rows);saveStocks();render();alert(`${rows.length} stocks imported.`)};r.readAsText(file);e.target.value=""}
function exportCSV(){const h=["Symbol","Company","Sector","Setup","Level","Entry","StopLoss","Target","Chartink","TradingView","Why","Notes","Favourite"],rows=stocks.map(s=>[s.symbol,s.company,s.sector,s.setup,s.level,s.entry,s.stop,s.target,s.chartink,s.tradingview,s.why,s.notes,s.favourite]),csv=[h,...rows].map(r=>r.map(v=>`"${String(v??"").replaceAll('"','""')}"`).join(",")).join("\n"),a=document.createElement("a");a.href=URL.createObjectURL(new Blob([csv],{type:"text/csv"}));a.download="stockstory-watchlist.csv";a.click()}
function closeModals(){document.getElementById("stockModal").classList.add("hidden");document.getElementById("journalModal").classList.add("hidden")}
document.querySelectorAll("nav button").forEach(b=>b.onclick=()=>{document.querySelectorAll("nav button").forEach(x=>x.classList.remove("active"));document.querySelectorAll(".page").forEach(x=>x.classList.remove("active"));b.classList.add("active");document.getElementById(b.dataset.page).classList.add("active")});
render();
